name: Node.js Express CD with Docker Hub

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build-and-push: # build and push to docker
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 # checkout JS and Docker File
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and Push Docker Image # Build on cloud
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/eshopweb:latest